title: XiaoZiLee's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "xiaozilee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: mmistakes/minimal-mistakes
logo: /assets/images/logo.jpg
plugins:
  - jekyll-include-cache
collections:
  notes:
    output: true
    permalink: /:collection/:name/